@baseurl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
# @name createAccount
POST {{baseurl}}/accounts
Content-Type: application/json

{
  "name": "John",
  "email": "johsn@example.com",
  "password": "password123"
}

###
# @name authenticate
POST {{baseurl}}/sessions
Content-Type: application/json

{
  "email": "john@example.com", 
  "password": "password123"
}
###

# @name create-question 
POST {{baseurl}}/questions
Content-Type: application/json
authorization: Bearer {{authToken}}